version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - postgres_db
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
