version: '3.8'

services:
  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app  # Mapea correctamente la carpeta backend en /app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    command: ["python", "/app/manage.py", "runserver", "0.0.0.0:8000"]
