version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Se mantiene el mapeo para desarrollo
    depends_on:
      - postgres_db
    restart: always


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app  # Asegurar que está bien mapeado
    depends_on:
      - backend
    restart: always

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    restart: always
